namespace Helix;

/// <summary>
/// Zero-reflection dispatch contract. Implementations are source-generated by Helix.Generator
/// and contain one typed <c>Execute_X</c> method per registered request type that calls
/// pre-processors, validators, behaviors, the handler, and post-processors entirely through
/// compile-time generics — no <see cref="System.Type.MakeGenericType"/> or
/// <see cref="System.Reflection.MethodInfo.Invoke"/> on the hot path.
/// </summary>
/// <remarks>
/// Register the generated implementation via <c>services.AddHelix(...).UseHelixCodeGen()</c>.
/// <see cref="DefaultHelix"/> automatically uses it when present in the DI container, and
/// falls back to the reflection-based path for any request type not covered by the table.
/// </remarks>
public interface IHelixDispatchTable
{
    /// <summary>
    /// Attempts to execute the full request pipeline (pre-processors → validators →
    /// behaviors → handler → post-processors) without reflection.
    /// Returns <see langword="false"/> when no generated entry exists for the concrete
    /// request type, signalling <see cref="DefaultHelix"/> to fall back to reflection.
    /// </summary>
    bool TryDispatch<TResponse>(
        IRequest<TResponse> request,
        CancellationToken ct,
        out Task<TResponse> result);

    /// <summary>
    /// Attempts to execute a streaming request handler without reflection.
    /// Returns <see langword="false"/> when no generated entry exists for the concrete
    /// request type.
    /// </summary>
    bool TryDispatchStream<TResponse>(
        IStreamRequest<TResponse> request,
        CancellationToken ct,
        out IAsyncEnumerable<TResponse> result);
}
